# Generated by Django 5.1.4 on 2025-01-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leafletjs_maps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="status",
            field=models.CharField(default="Aguardando entrega", max_length=255),
        ),
    ]
